global:
  scrape_interval: 10s # Default is 1min
# Node exporter is prometheus exporter that collect and expose detailed system-level metrics
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter1:9100']
        labels:
          group: 'monitoring_node1'
      - targets: ['node-exporter2:9100']
        labels:
          group: 'monitoring_node2'
      - targets: ['node-exporter3:9100']
        labels:
          group: 'monitoring_node3'
  - job_name: 'monitorPythonserver'
    static_configs:
      - targets: ['pythonserver:8080']
        labels:
          group: 'monitoring_python'